# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('word', models.CharField(max_length=2048)),
                ('method', models.CharField(choices=[('TFIDF', 'Term Frequency/Inverse Document Frequency')], max_length=5)),
                ('score', models.FloatField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to='profiles.Speech')),
            ],
        ),
    ]
