# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('common_name', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('birth_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('deceased_date', models.DateField(blank=True, null=True)),
                ('death_location', models.CharField(blank=True, max_length=1024, null=True)),
                ('education', models.CharField(blank=True, max_length=1024, null=True)),
                ('years_lived', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-birth_date'],
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Person')),
                ('elections_won', models.PositiveSmallIntegerField(default=0)),
                ('presidecy_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_year', models.DateTimeField(blank=True, null=True)),
                ('end_year', models.DateTimeField(blank=True, null=True)),
                ('reason_left_office', models.CharField(choices=[('NSR', 'Did Not Seek Re-election'), ('TME', 'Term Ended'), ('LRE', 'Lost'), ('DIO', 'Died in Office'), ('ASN', 'Assasinated'), ('RSG', 'Resigned'), ('IPH', 'Impeached')], default='TME', max_length=3)),
                ('ari_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wordcloud', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            bases=('profiles.person',),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('first_name', 'middle_name', 'last_name')]),
        ),
        migrations.AddField(
            model_name='speech',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='profiles.President'),
        ),
    ]
