# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='ARI_display',
            field=models.CharField(default='Not Scored Yet.', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='speech',
            name='ARI_score',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
