# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
