# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161124_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='president',
            old_name='presidency_start_year',
            new_name='start_year',
        ),
        migrations.AddField(
            model_name='person',
            name='death_location',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='president',
            name='reason_left_office',
            field=models.CharField(choices=[('NSR', 'Did Not Seek Re-election'), ('TME', 'Term Ended'), ('LRE', 'Lost'), ('DIO', 'Died in Office'), ('ASN', 'Assasinated'), ('RSG', 'Resigned'), ('IPH', 'Impeached')], default='IPH', max_length=3),
            preserve_default=False,
        ),
    ]
