# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_speech_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='delivery_date',
            new_name='date',
        ),
    ]
