# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20161124_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='president',
            old_name='presidency_end_year',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='president',
            name='elections_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='president',
            name='wordcloud',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
